Fix for API change in pg8000 1.17
pg8000 version 1.17 has an API change (https://github.com/tlocke/pg8000#version-1-17-0-2021-01-30) that leads to the following error:

  File "allensdk/internal/core/lims_utilities.py", line 82, in <listcomp>
    columns = [ d[0].decode("utf-8") for d in cursor.description ]
AttributeError: 'str' object has no attribute 'decode'